name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-14", "windows-latest"]
          # - ubuntu-latest
          # - macos-14
          # - windows-latest
        py-version: ["3.10", "3.11", "3.12"]
          # - "3.10"  # we can also specify this way, otherwise 0 is truncated!
          # - "3.11"
          # - "3.12"
        exclude:
          - os: "macos-14"
            py-version: "3.12"
    runs-on: '${{ matrix.os }}'
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ matrix.py-version }}'

